version: '3.8'

services:
  ipfs:
    image: ipfs/go-ipfs:latest
    ports:
      - "5001:5001"
    volumes:
      - ipfs-data:/data/ipfs

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mydbpassword
      POSTGRES_DB: graph-node
      POSTGRES_INITDB_ARGS: "--locale=C --encoding=UTF8"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  graph-node:
    image: graphprotocol/graph-node:latest
    ports:
      - "8000:8000"
      - "8001:8001"
      - "8020:8020"
    environment:
      postgres_host: postgres
      postgres_user: postgres
      postgres_pass: mydbpassword
      postgres_db: graph-node
      ipfs: 'ipfs:5001'
      ethereum: 'evmos:https://proxy.evmos.org/web3'
      GRAPH_LOG: debug

volumes:
  ipfs-data:
  postgres-data:
